# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
