# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190301_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
